config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "rovers#index"
  resources :rovers do
    resources :images, only: [:show]
  end
  resources :images do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resources :votes, only: [:create]
  end
  namespace :api do
    namespace :v1 do
      resources :comments, only: [:create]
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  validates :body, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :rover
  has_many :comments
  has_many :votes

  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
end

app/models/rover.rb
class Rover < ActiveRecord::Base
  has_many :images

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :votes

  validates :first_name, presence: true
  validates :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  validates :vote, inclusion: { in: [true, false, 1, 0] }
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::Base
  protect_from_forgery with: :null_session

  def create
    comment = Comment.new(comment_params)
    if comment.save
      render json: {
        id: comment.id,
        comment: comment,
        user: current_user
      }
    else
      render json: :nothing, status: :not_found
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :image_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @image = Image.find(params[:image_id])
    @comment = Comment.new
    @comments = @image.comments
  end

  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to image_path(@image)
    else
      flash[:errors] = @comment.errors.full_messages.join(". ")
      render :show
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      flash[:errors] = @comment.errors.full_messages.join(". ")
      render :show
    end
    @image = @comment.image
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to image_path(@comment.image)
    else
      flash[:notice] = "You must fill out all of the required fields"
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:image_id])
    Comment.find(params[:id]).destroy

    redirect_to image_path(@image)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :image_id, :user_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments
  end
end

app/controllers/rovers_controller.rb
class RoversController < ApplicationController
  def index
    @rovers = Rover.all
  end

  def show
    @rover = Rover.find(params[:id])
    @images = @rover.images
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    new_vote = params[:newVote]
    i_id = params[:iId].to_i

    vote = Vote.find_by(user: current_user, image_id: i_id)

    if vote
      if vote.vote == (new_vote == 'upvote')
        vote.destroy
      else
        vote.vote = !vote.vote
        vote.save
      end
    else
      Vote.create(
        user: current_user,
        image_id: i_id,
        vote: new_vote == 'upvote'
      )
    end

    render json: {
      upvotes: Vote.where(image_id: i_id, vote: true).count,
      downvotes: Vote.where(image_id: i_id, vote: false).count
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_for [@image, @comment] do |f| %>
  <div class="form-inputs">
    <%= f.label :body, "Comment" %>
    <%= f.text_field :body %>
  </div>

  <div class="form-actions">
    <%= f.submit "Update Comment", class: "small button", id: "create comment" %>
  </div>
<% end %>

app/views/images/show.html.erb
<div class="return"> <%= link_to "Back to #{@image.rover.name} images", rover_path(@image.rover), class: "link" %> </div>
<h4 class="image-title">Photo taken by <%= @image.name %> with the <%= @image.description %> </h4>
<div class="full-size-image" image-id="<%= @image.id %>"> <%= image_tag ("#{@image.image}") %> </div>


<% if user_signed_in? %>
  <div class="vote-buttons">
    <%= button_to pluralize(@image.votes.where(vote: true).count,
      "Upvote"),
      image_path(@image),
      method: 'get',
      class: 'votes up tiny button',
      id: "upvote-#{@image.id}" %>
    <%= button_to pluralize(@image.votes.where(vote: false).count,
      "Downvote"),
      image_path(@image),
      method: 'get',
      class: 'votes down tiny button',
      id: "downvote-#{@image.id}" %>
  </div>
  <% else %>
    <div id="sign-in-request"><%= link_to "Sign in to vote and comment!", new_user_session_path, class: "link"%></div>
<% end %>

<% if @comments.empty? %>
<p class="comments-empty">No comments to display!</p>
<% end %>

<div class="comment-box">
  <% @comments.each_with_index do |comment, index| %>
  <div class="comment-wrapper" comment-id="<%= comment.id %>">
    <div class="comment-actions">
      <% if current_user == comment.user %>
      <li><%= link_to "Edit Comment", edit_image_comment_path(@image, comment), class: "link edit-comment" %></li>
      <li><%= link_to "Delete Comment", image_comment_path(@image, comment), class: "link delete-comment", id: "delete", method: :delete %></li>
      <% end %>
    </div>
    <li class="name", id="username"><%= comment.user.first_name %> <%= comment.user.last_name %></li>
    <li class="body", id="comment-body"><%= comment.body %></li>
    <!-- <li class="timestamp" id="timestamp[<%= index %>]"> <%=comment.user.created_at%> </li> -->
  </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <h2>New Comment</h2>
  <div class="row comment-form">
    <div class="small-6 small-centered columns border">
      <%= form_for [@image, @comment] do |f| %>
      <div class="form-inputs">
        <%= f.label :body, "Comment" %>
        <%= f.text_area :body %>
      </div>
      <div class="form-actions">
        <%= f.submit class: "small button form-button", id: "comment-form" %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Red Planet</title>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href=" <%= root_path %> ">Red Planet</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
          <li class="has-dropdown">
          <a href="#" user-info="#" id="<%=current_user.id%>"> <%= current_user.first_name %> <%= current_user.last_name %> </a>
            <ul class="dropdown">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="active"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
          <% else %>
          <li class="active"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="active"><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>

      <div class="notice"><%= flash[:notice] %></div>
      <div class="alert"><%= flash[:alert] %></div>

    <%= yield %>

  </body>
</html>

app/views/rovers/index.html.erb
<div class="cover-body"></div>
<div class="rover-body">
  <h2>Choose a Rover</h2>
  <% @rovers.each do |rover| %>
  <div class="rover-wrapper">
    <li class="rover-image"><%= link_to (image_tag "#{rover.image_url}"), rover_path(rover) %></li>
    <li class="rover-title">
      <%= link_to "#{rover.name} ", rover_path(rover), class: "full-title" %>
    </li>
  </div>
  <% end %>
</div>

app/views/rovers/show.html.erb
<div class="return"> <%= link_to "Home", root_path, class: "link" %> </div>
<h2 class="rover-name"><%= @rover.name %></h2>

<p class="rover-description"><%= @rover.description %></p>
<div class="page-guide">Click on the thumbnails below to see these images in all their glory!</div>
<div class="image-body">
  <% @images.each do |image| %>
  <div class="image-wrapper">
    <li class="image"><%= link_to (image_tag ("#{image.image}")), rover_image_path(@rover, image), class: "img-link" %></li>
  </div>
  <% end %>
</div>